"""Release gate: reject ambiguous patches, preserve user work, validate XML."""
import importlib.util
import tempfile
import subprocess
import sys
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

spec = importlib.util.spec_from_file_location('reliability_tool', Path(__file__).parents[1] / 'keil_port_tool.py')
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)

MAIN = ('/* USER CODE END Includes */\nint main(void) {\n'
        'HAL_Init();\n/* USER CODE END 2 */\nwhile (1) {}\n}\n')
IRQ = ('/* USER CODE END Includes */\nvoid PendSV_Handler(void) { }\n'
       'void HardFault_Handler(void) { while (1) {} }\n'
       'void SysTick_Handler(void) {\n/* USER CODE END SysTick_IRQn 0 */\nHAL_IncTick();\n}\n')


def xml():
    target = ('<Target><TargetName>{}</TargetName><TargetOption><TargetArmAds><Cads>'
              '<VariousControls><Define>BASE</Define><IncludePath/></VariousControls>'
              '</Cads></TargetArmAds></TargetOption><Groups/></Target>')
    return '<Project><Targets>' + target.format('Debug') + target.format('Release') + '</Targets></Project>'


class Patches(unittest.TestCase):
    def test_runtime_integration_guidance_is_generated(self):
        self.assertIn('osThreadExit()', m.freertos_app_templates(True)[1])
        self.assertIn('vTaskDelete(NULL)', m.freertos_app_templates(False)[1])
        with tempfile.TemporaryDirectory() as directory:
            source = m.fatfs_diskio_templates(Path(directory))[1]
        self.assertIn('FIFO service timing', source)
        self.assertIn('not F407 CCM', source)
        self.assertIn('main/task stack', source)

    def test_modules_import_without_gui_or_entry_point(self):
        result = subprocess.run([sys.executable, '-c',
            "import sys; from kps_core.source_patches import patch_main_start_scheduler; "
            "from kps_core.ownership import _edit_hunks; from kps_core.runtime import operation_context; "
            "assert 'tkinter' not in sys.modules; assert 'keil_port_tool' not in sys.modules"],
            cwd=str(Path(__file__).parents[1]), capture_output=True)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_guard_must_cover_actual_wrapper_function(self):
        source = '#if defined(SysTick)\n#undef SysTick_Handler\n#endif\nvoid SysTick_Handler(void) {}'
        with self.assertRaises(m.ToolError):
            m.patch_cmsis_wrapper_systick(source).require_safe('wrapper.c')

    def test_unguarded_tick_is_not_considered_valid(self):
        source = 'void SysTick_Handler(void) { xPortSysTickHandler(); }'
        with self.assertRaises(m.ToolError):
            m.patch_project_systick(source).require_safe('irq.c')

    def test_language_catalog_does_not_silently_lose_keys(self):
        self.assertEqual(len(m._EN_MESSAGES), len(m._ZH_MESSAGES))
        with self.assertRaises(ValueError):
            m._reverse_message_catalog({'one': 'same', 'two': 'same'})

    def test_lwip_user_header_not_upgraded_by_comment(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / 'cc.h'
            original = '/* user header mentions lwip_errno */\n#define LWIP_ARCH_CC_H\n#define BYTE_ORDER LITTLE_ENDIAN\n'
            path.write_text(original, encoding='utf-8')
            report = m.Report('lwip')
            self.assertFalse(m._plan_lwip_errno_upgrade(path, 'test', report))
            self.assertFalse(report.gen_files)
            self.assertTrue(report.warnings)
            path.write_text('/* Generated by keil_port_tool.py. */\n' + original, encoding='utf-8')
            self.assertTrue(m._plan_lwip_errno_upgrade(path, 'test', report))
            self.assertIn('extern int lwip_errno;', report.gen_files[0][1])

    def test_main_comments_do_not_count_as_start(self):
        original = MAIN.replace('HAL_Init();', '/* osKernelStart(); */\nHAL_Init();')
        result = m.patch_main_start_scheduler(original).require_safe('main.c')
        self.assertTrue(result.changed)
        self.assertEqual(m.patch_main_start_scheduler(result.text).status, 'already_correct')

    def test_main_partial_and_conditional_start_blocked(self):
        cases = [MAIN.replace('HAL_Init();', 'osKernelStart();'),
                 MAIN.replace('HAL_Init();', 'if (enabled) { osKernelStart(); }'),
                 MAIN.replace('HAL_Init();', 'if (failed) return 1;'),
                 MAIN.replace('int main', 'int application')]
        for source in cases:
            with self.subTest(source=source):
                result = m.patch_main_start_scheduler(source)
                self.assertFalse(result.changed)
                with self.assertRaises(m.ToolError):
                    result.require_safe('main.c')

    def test_handlers_user_logic_preserved_atomically(self):
        source = 'void SVC_Handler(void) { /* empty */ }\nvoid PendSV_Handler(void) { user(); }'
        result = m.patch_project_rtos_exceptions(source)
        self.assertEqual(result.status, 'conflict')
        self.assertEqual(result.text, source)
        duplicate = 'void SVC_Handler(void) {}\nvoid SVC_Handler(void) {}'
        self.assertEqual(m.patch_project_rtos_exceptions(duplicate).status, 'unsupported')

    def test_wrapper_unknown_fails_not_silent(self):
        for source in ('#if SOME_NEW_LAYOUT\nvoid SysTick_Handler(void) {}\n#endif',
                       '/* #if defined(SysTick)\n#undef SysTick_Handler */'):
            with self.assertRaises(m.ToolError):
                m.patch_cmsis_wrapper_systick(source).require_safe('wrapper.c')
        source = '#if defined ( SysTick )\r\n  #undef SysTick_Handler\r\nvoid SysTick_Handler(void) {}\r\n#endif'
        result = m.patch_cmsis_wrapper_systick(source).require_safe('wrapper.c')
        self.assertTrue(result.changed)
        self.assertFalse(m.patch_cmsis_wrapper_systick(result.text).changed)

    def test_rtthread_partial_patch_still_checks_vectors(self):
        patched = m.patch_rtthread_irq(IRQ)
        self.assertEqual(m.patch_rtthread_irq(patched), patched)
        partial = IRQ.replace('HAL_IncTick();', 'KPS_RTTHREAD_Tick();\nHAL_IncTick();')
        fixed = m.patch_rtthread_irq(partial)
        self.assertEqual(fixed.count('#if !defined(KPS_USING_RTTHREAD)'), 2)
        with self.assertRaises(m.ToolError):
            m.patch_rtthread_irq(partial.replace('while (1) {}', 'save_crash(); while (1) {}'))

    def test_rtthread_comment_does_not_count(self):
        result = m.patch_rtthread_irq(IRQ.replace('HAL_IncTick();', '/* KPS_RTTHREAD_Tick(); */\nHAL_IncTick();'))
        self.assertIn('KPS_RTTHREAD_Tick();', m._c_code(result))


class Ownership(unittest.TestCase):
    def test_hunks_roundtrip_newlines_and_unrelated_changes(self):
        for before, after in ((IRQ, m.patch_rtthread_irq(IRQ)),
                              (MAIN, m.patch_main_start_scheduler(MAIN).text)):
            hunks = m._edit_hunks(before, after)
            changed = '// user added a note\n' + after.replace('\n', '\r\n')
            restored = m._reverse_owned_hunks(changed, hunks, 'arbitrary_irq.c')
            self.assertEqual(restored, '// user added a note\n' + before)

    def test_touched_owned_region_blocks(self):
        after = m.patch_main_start_scheduler(MAIN).text
        edited = after.replace('MX_FREERTOS_Init();', 'MyTasks();')
        with self.assertRaises(m.ToolError):
            m._reverse_owned_hunks(edited, m._edit_hunks(MAIN, after), 'main.c')

    def test_install_uninstall_arbitrary_irq_filename(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            project = root / 'test.uvprojx'
            project.write_text(xml(), encoding='utf-8')
            irq = root / 'CustomBoard' / 'stm32h7xx_it.c'
            irq.parent.mkdir()
            irq.write_text(IRQ, encoding='utf-8')
            opts = SimpleNamespace(yes=True, dry_run=False)
            def task(proj, opts, report):
                report.gen_files.append((irq, m.patch_rtthread_irq(m.read_source_text(irq)), 'IRQ'))
                proj.add_define('KPS_USING_RTTHREAD', report)
            with patch.dict(m.TASK_FUNCS, {'rtthread': task}):
                self.assertTrue(m.run_tasks(m.KeilProject(project), ['rtthread'], opts))
            installed = m.installed_components(m.KeilProject(project))['rtthread']
            self.assertTrue(installed['source_edits_complete'])
            self.assertIn('stm32h7xx_it.c', installed['source_edits'][0]['path'])
            irq.write_bytes(m.encode_preserving_format(irq, '// unrelated user note\n' + m.read_source_text(irq)))
            self.assertTrue(m.uninstall_component(m.KeilProject(project), 'rtthread', yes=True))
            self.assertEqual(m.read_source_text(irq).replace('\r\n', '\n'), '// unrelated user note\n' + IRQ)

    def test_legacy_manifest_is_not_guessed(self):
        with self.assertRaises(m.ToolError):
            m._manifest_source_unpatches(None, 'rtthread', {'generated_files': [{'created': False}]})


class XMLSafety(unittest.TestCase):
    def test_selected_only_and_roundtrip_guard(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / 'test.uvprojx'
            path.write_text(xml(), encoding='utf-8')
            proj = m.KeilProject(path)
            proj.select_targets(['Debug'])
            proj.add_file('New group', 'test.c', 1, 'test.c')
            payload = proj.serialize()
            self.assertIn(b'New group', payload)
            with self.assertRaises(m.ToolError):
                proj.validate_serialized(payload.replace(b'test.c', b'other.c'))
            proj.all_targets[1].find('TargetName').text = 'Accidental edit'
            with self.assertRaises(m.ToolError):
                proj.serialize()

    def test_external_xml_edit_not_overwritten(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / 'test.uvprojx'
            path.write_text(xml(), encoding='utf-8')
            proj = m.KeilProject(path)
            proj.add_define('NEW', m.Report('add_files'))
            changed = xml().replace('BASE', 'USER_EDIT')
            path.write_text(changed, encoding='utf-8')
            with self.assertRaises(m.ToolError):
                proj.save()
            self.assertEqual(path.read_text(encoding='utf-8'), changed)


if __name__ == '__main__':
    unittest.main()
